### PR TITLE
change C# to C(sharp)

### PR DESCRIPTION
**Pull request by pandeyji711**
@jfmartinz please review and merge

### CODE REVIEW

**Comment by priyanshukumar397** [comment]
@sanjay-kv kindly look into this one as well - updating docs should not be awarded points until there is a typo

**Comment by pandeyji711** [comment]
@priyanshukumar397 becouse of api unable to fetch when the name in C# but it work when it rename to C(sharp) 
thats whay i change , why are you targeting me...

**Comment by priyanshukumar397** [comment]
Nobody is targeting you - as a contributor you should mention clearly what are you updating and why? I do not see any doc or summary from your side

**Comment by pandeyji711** [comment]
@priyanshukumar397 Sir I am just doning my job as Contributor You filtered my 200+ points

**Comment by priyanshukumar397** [comment]
Kindly add doc as well or a summary for a better understanding and do your job properly sir, I have mentioned it for everyone - regarding points I did not do that - that is for - @sanjay-kv

**Comment by pandeyji711** [comment]
> Kindly add doc as well or a summary for a better understanding and do your job properly sir, I have mentioned it for everyone - regarding points I did not do that - that is for - @sanjay-kv

@priyanshukumar397  ok got it

**Comment by sanjay-kv** [comment]
@pandeyji711 appologies for the wrong approach from my team side. I will have a look into it, we getting reported your name in discord . Maybe that's why the team commented here. I will do manual reviews if needed and confirm via official channels.

**Comment by pandeyji711** [comment]
> @pandeyji711 appologies for the wrong approach from my team side. I will have a look into it, we getting reported your name in discord . Maybe that's why the team commented here. I will do manual reviews if needed and confirm via official channels.

@sanjay-kv Thankyou sir for your confirmation

**Pull request merged**
