### PR TITLE
Added Challenges section to data science resources

### LINKED ISSUE #320: 💡 [FEATURE] - Add "Community and Forums" Section to Data Science Resources
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The current Data Science resources page provides a comprehensive list of tools, technologies, courses, books, and YouTube channels. However, it lacks a dedicated section for communities and forums. These platforms are vital for data science enthusiasts and professionals as they offer spaces to ask questions, share knowledge, and collaborate on projects. Including a "Community and Forums" section would enhance the resource collection by providing avenues for ongoing learning and community engagement.

### Explain your solution

To address this gap, I propose adding a new section titled "Community and Forums" to the Data Science resources page. This section would include a table listing several prominent communities and forums where users can engage with others in the data science field. The table should include the name of the community, a brief description, and a link to the platform.

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### LINKED ISSUE #321: 💡 [FEATURE] - Add "Competitions" Section to Data Science Resources
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The current Data Science resources page lacks a section for competitions. Competitions are valuable for practicing and showcasing data science skills, but there's no dedicated place for users to find these opportunities.

### Explain your solution

Add a new section titled "Competitions" to the Data Science resources page. This section should include a table with the names, descriptions, and links to platforms that host data science competitions.

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SkSadaf**
PR Title: Added Challenges section and Communities section to data science resources

### Closes Issue
Closes #321 
Closes #320 

### Description: 
Added a new section titled "Challenges" to the Data Science resources page. This section includes a table with the names, descriptions, and links to platforms that host data science challenges.  The "Communities" section includes a table listing prominent communities where users can engage with others in the data science field. The table includes the name of the community, a brief description, and a link to the platform.

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [YES ] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [YES ] I followed the prescribed PR title template.

### CODE REVIEW

**Comment by jfmartinz** [comment]
Yes, it is really indeed a Competitions. You can replace it as Competitions, sorrry. Also next time, create seperate PR for each issue, thanks

**Comment by SkSadaf** [comment]
Sure, I will replace "Challenges" with "Competitions" as requested.

The reason I created a single PR for two issues is that GitHub doesn't allow creating another pull request until the current one is merged. I thought combining them would save time. However, as you requested, I will create separate PRs for each issue from now on.

Thank you for the feedback!

**Comment by jfmartinz** [comment]
> Sure, I will replace "Challenges" with "Competitions" as requested.
> 
> The reason I created a single PR for two issues is that GitHub doesn't allow creating another pull request until the current one is merged. I thought combining them would save time. However, as you requested, I will create separate PRs for each issue from now on.
> 
> Thank you for the feedback!

Yes, because I am just worried about the points.  Thanks for understanding

**Comment by jfmartinz** [comment]
I will try to merged your PR as possible, just busy with school. But if you want you can reach out tome to some of my socials

**Review by jfmartinz — APPROVED** [review]
Looks good!

**Pull request merged**
