### PR TITLE
Create README.md for solving #1326

### LINKED ISSUE #1326: ➕ [RESOURCE] - Blockchain all resources
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

its a separate whole resource i want to add

### Provide the URLs of the resources you are adding

_No response_

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
# Pull Request

## Description
Please include a summary of the changes and the related issue.  
Blockchain involves the practice of creating, managing, and securing decentralized and distributed digital ledgers. It includes measures and protocols designed to ensure data integrity, transparency, and immutability. Blockchain encompasses consensus algorithms, smart contracts, decentralized applications, and continuous innovation to ensure robust and secure digital transactions.

Closes #1326 

## Type of change
- [ ] Adding a new Resource
- [x] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@jfmartinz 
Kindly review and merge the PR

**Comment by jfmartinz** [comment]
Please read CONTRIBUTING.md. You didnt follow the format for adding tables.

**Comment by Aditi22Bansal** [comment]
@jfmartinz 
Kindly review now and approve

**Review by jfmartinz — CHANGES_REQUESTED** [review]
Also Table of Contents links are not working. 

image

**Comment by Aditi22Bansal** [comment]
@jfmartinz 
Done the required changes
Kindly review now

**Review by jfmartinz — CHANGES_REQUESTED** [review]
Not working:

image

[Check](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#section-links)

**Comment by Aditi22Bansal** [comment]
@jfmartinz 
Kindly check now

**Review by jfmartinz — APPROVED** [review]

**Pull request merged**
