### PR TITLE
Add Complete MongoDB resources

### LINKED ISSUE #926: 💡 [FEATURE] - Add Complete MongoDB resources
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

_No response_

### Explain your solution

I want to add the  mongodb complete resources.

### Any alternative approaches/features

_No response_

### Additional Context

COuld you assign me @jf

### PR DESCRIPTION
**Pull request by jayraj175coder**
#926  Add Complete  MOngoDB resources.

## Description
I add the whole resources of mongoDB .

Closes #926

## Type of change
- [ ] Adding a new COmplETE Resource

## Checklist:
- [ ] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

### CODE REVIEW

**Review by jfmartinz — CHANGES_REQUESTED** [review]
You forgot to add an extension 'md' to your readme file, check your work.

**Comment by jayraj175coder** [comment]
Done add .md extension @jfmartinz .

**Comment by jfmartinz** [comment]
Hi. Sorry I announced it late, maybe you can add this into this [folder](https://github.com/jfmartinz/ResourceHub/tree/main/DBMS%20(Database)). Just moved it and push another commit and then I will merged this PR, tahnks

**Comment by jayraj175coder** [comment]
Hi @jfmartinz Done move to databse.

Thanks..

**Review by jfmartinz — APPROVED** [review]

**Pull request merged**
