### PR TITLE
Fixed "Back-to-Top Button" Color "Issues" in Dark Mode and Added Button to All Pages

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Description

Hey @jfmartinz 

This pull request addresses the following issues with the **"Back to Top"** button on the Resource Hub website:

- **Color Issue in Dark Mode:** The "Back to Top" button had visibility issues in dark mode. 
    - In light mode, the button was black with a white arrow, but in dark mode, it turned completely white, making it invisible. 
    - This has been fixed so that in dark mode, the button is white with a black arrow. 
    - Additionally, hover effects have been added for better user experience.
- **Button Availability on Resources Pages:** The "Back to Top" button was only present on the main page. It has now been added to resource pages, to improve navigation. (the back to top button was specially needed for them)

### Changes Made:

- **Updated the CSS** for the "Back to Top" button to ensure it is visible
- Light Mode: **Black button with a white arrow.**
- Dark Mode: **White button with a black arrow.**
- **Added hover effects** to the button for better visual feedback.
- **Integrated the "Back to Top" button into all resource pages** for consistent navigation.

### Screenshots

https://github.com/jfmartinz/ResourceHub/assets/101971980/09862253-ec0f-41f5-8120-53e8ce75c674

Please take a look and review it, thank you!

## Type of change

- [x] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by jfmartinz** [comment]
Solve the conflict so I can merged this PR

**Comment by MastanSayyad** [comment]
@jfmartinz conflicts are resolved

**Comment by MastanSayyad** [comment]
@jfmartinz

**Comment by MastanSayyad** [comment]
Hey @jfmartinz  please take a look and merge this PR

**Comment by jfmartinz** [comment]
Please resolve the conflict, thanks

**Comment by jfmartinz** [comment]
Sorry hehe

**Comment by MastanSayyad** [comment]
> Sorry hehe

I can see you knew what you did 😂😂

**Comment by MastanSayyad** [comment]
> Please resolve the conflict, thanks

Done @jfmartinz, Conflicts are resolved

**Comment by jfmartinz** [comment]
Thanks @MastanSayyad  as always. Your contributions are very helpful

**Pull request merged**
