### PR TITLE
Website - Responsive to different screen sizes.

### LINKED ISSUE #722: 🐞 [BUG] - Responsiveness of the website
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The website is not responsivee.

### Expected behavior

I would like to make the website responsive for every device sixe.

SCREENSHOT

Screenshot (527)

### Steps to reproduce

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by yashi-15**
Closes #722

Kindly review and merge this PR under GSSOC'24.

### Screenshot (BEFORE):
Screenshot (527)
Screenshot (568)

### Screenshot (AFTER):
Screenshot (563)
Screenshot (567)

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Comment by jfmartinz** [comment]
Conflict

**Comment by yashi-15** [comment]
conflict resolved, @jfmartinz

**Comment by yashi-15** [comment]
@jfmartinz Kindly review now..

**Comment by jfmartinz** [comment]
There are still conflict

**Comment by yashi-15** [comment]
@jfmartinz Resolved !

**Pull request closed without merging**
