### PR TITLE
Formatting of Python Resources

### PR DESCRIPTION
**Pull request by sau-mili**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

Deleted unnecessary rows
Deleted extra info of child categories
Header names changed 
Overall formatting of resources under Python Category

- 
-
-

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Review by jfmartinz — CHANGES_REQUESTED** [review]
Remove these white texts in the book section:
image

And then I can merged, thanks

**Comment by sau-mili** [comment]
I have removed those

**Review by jfmartinz — APPROVED** [review]
Thanks, looks good!

**Comment by jfmartinz** [comment]
Another problem, theres a conflict, can you resolve it

**Comment by sau-mili** [comment]
Like last time, the resolve option is greyed out on my side.. I think it’s because I don’t have writing access to the merges. So you would need to resolve it

**Comment by jfmartinz** [comment]
Read "Conflicts generally arise when two people have changed the same lines in a file, or if one developer deleted a file while another developer was modifying it. In these cases, Git cannot automatically determine what is correct." 

You just need to push another commit that will determine  which changes you want.  check this [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

"resolving conflicts is typically the responsibility of the person who made the changes, as they have the best understanding of how to properly integrate their work."

**Comment by sau-mili** [comment]
I have read this article, but in my case it doesn’t show the option to merge. In this pull, I made a lot of changes already. It just shows “discard commits” when I try to sync the repo

**Comment by jfmartinz** [comment]
In my end:
image

The Python folder was moved thats why its conflicting.  

Maybe create another PR. And make sure to git pull to make your branch up to date to the main

**Comment by sau-mili** [comment]
Same on my end.. should I close this and create a new pull req?

**Comment by jfmartinz** [comment]
Sure

**Pull request closed without merging**
