### PR TITLE
Add labels

### LINKED ISSUE #794: Automate Labeling of Pull Requests
Implement a bot or script to automatically suggest labels based on the content of pull requests. Include a review step to ensure the suggested labels are accurate. This will streamline the labeling process and improve organization.

### PR DESCRIPTION
**Pull request by hars-21**
# Pull Request

## Description
Added auto label file which will automatically add gssoc label to all the issues. This will enhance the workflow

Closes #794 

## Type of change
- [x] Documentation enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

### CODE REVIEW

**Comment by jfmartinz** [comment]
Also for PR raised?

**Comment by jfmartinz** [comment]
Add the automation for PR. If possible add it in a single file

**Comment by hars-21** [comment]
It will add label on both issue and PR.

**Comment by jfmartinz** [comment]
I will merged it for now. I cant see the code.

**Pull request merged**
