### PR TITLE
Machine Learning - Added "Machine Learning Courses"

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Description

Hey @jfmartinz I have Added some additional free Courses in the Machine Learning Directory,
Please take a look and review it, Thank You!!

## Type of change
- [x] Adding a new Resource
- [x] Adding a new Category
- [x] Documentation enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by jfmartinz — APPROVED** [review]

**Comment by MastanSayyad** [comment]
@jfmartinz pls merge this PR

**Comment by MastanSayyad** [comment]
Also In DBMS (Database) directory, we should add resources for all Databases just like we did for all Programming Languages. This will allow other contributors to add other database resources and stop spamming in the existing resource directories.

The DB Resources folder structure may look like this:

``` 
.
├─ DBMS (Databases)
│  ├── DBMS Overview 
│  └── readme.md    -----> current readme.md file which will work as an Introduction, Summary or quick overview of DBMS
│  │ 
│  ├── MySQL
│  └── readme.md
│  │ 
│  ├── PostgreSQL
│  └── readme.md
│  │ 
│  ├── SQLite
│  └── readme.md
│
└─── Other Databases...and So on...
   
``` 

@jfmartinz Let me know If it sounds good, Thank You !!

**Comment by jfmartinz** [comment]
> Also In DBMS (Database) directory, we should add resources for all Databases just like we did for all Programming Languages. This will allow other contributors to add other database resources and stop spamming in the existing resource directories.
> 
> The DB Resources folder structure may look like this:
> 
> ```
> .
> ├─ DBMS (Databases)
> │  ├── DBMS Overview 
> │  └── readme.md    -----> current readme.md file which will work as an Introduction, Summary or quick overview of DBMS
> │  │ 
> │  ├── MySQL
> │  └── readme.md
> │  │ 
> │  ├── PostgreSQL
> │  └── readme.md
> │  │ 
> │  ├── SQLite
> │  └── readme.md
> │
> └─── Other Databases...and So on...
>    
> ```
> 
> @jfmartinz Let me know If it sounds good, Thank You !!

Good Idea

**Comment by jfmartinz** [comment]
You can work on it

**Pull request merged**
