### PR TITLE
All categories - Conclusions added

### LINKED ISSUE #543: 💡 [FEATURE] - Add conclusion to All categories
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I saw that the conclusion section is present for only programming languages ,but even other categories requires conclusion. 

### Explain your solution

I would like to add conclusion to all the categories.

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by chaanakyaaM**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

Closes #543 

Conclustion are added to all categories except web development category.

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Review by jfmartinz — COMMENTED** [review]
Did you also add for web development?

**Comment by chaanakyaaM** [comment]
No,I shall I?

**Comment by jfmartinz** [comment]
Yes

**Comment by chaanakyaaM** [comment]
Done !

**Review by jfmartinz — APPROVED** [review]
thanks

**Pull request merged**
