### PR TITLE
Programming Languages - "R" Complete Resources

### LINKED ISSUE #372: 💡 [FEATURE] - Add 'R Programming Language' complete Resources
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

R Programming Language is missing, which is widely used for statistical computing, data analysis, and data visualization. It is popular in academia, research, and industry for its powerful data manipulation and graphical capabilities.

### Explain your solution

I propose adding resources for learning R from basics to advanced levels, which will include:

R Basics:

- Data types (vectors, lists, matrices, data frames)
- Variables and operators
- Control structures (if-else, loops)
- Functions

Data Manipulation:

- Importing and exporting data
- Data cleaning
- Data transformation with dplyr
 -Working with dates and times

Data Visualization:

- Base R graphics
- ggplot2 for advanced visualization
- Creating interactive visualizations with Shiny

Statistical Analysis:

- Descriptive statistics
- Inferential statistics
- Hypothesis testing
- Regression analysis (linear and logistic)

Advanced Topics:

- Working with large datasets
- Parallel computing
- Rcpp for integrating C++ code
- Creating R packages

Machine Learning:

- Introduction to machine learning with R
- Using caret and other machine learning packages
- Model evaluation and selection

Project Ideas:

- Real-world applications
- Sample projects

### Any alternative approaches/features

To enhance the learning experience, I suggest including important resources such as books, YouTube channels, and websites. This will provide comprehensive and accessible learning material. Additionally, I propose creating a beginner-friendly roadmap to guide learners through the resources step-by-step.

### Additional Context

This feature request aims to enrich the programming language section by providing extensive learning materials for R, similar to Python. This will cater to the high demand for R knowledge in data science, statistics, and research fields.

### PR DESCRIPTION
**Pull request by Santhosh-Siddhardha**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

Closes #372 

### Description: 
Hey @jfmartinz I have added all resources for R Programming Language
```
./Programming Languages
       /R
         / readme.md
```
Please take a look and do let me know,
Hope it helps. (also pls do not forget to add labels)

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Review by jfmartinz — APPROVED** [review]
Thanks

**Comment by Santhosh-Siddhardha** [comment]
@jfmartinz Please add gssoc and level badges

**Comment by jfmartinz** [comment]
I always forgot. haha, thanks

**Comment by Santhosh-Siddhardha** [comment]
@jfmartinz Please assign this PR to me.

**Pull request merged**
