### PR TITLE
[FEATURE]- Improve 404 Error page #359

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

Closes [#359 ]

Background Animation:

Added a background div containing three stars divs to create a parallax star field effect.
Applied different animation durations to the stars elements to create a layered movement effect.
CSS Animation for Background:

Created animStars keyframes to animate the background stars.
General Styling:

Adjusted overall styling and positioning to ensure the new background effect integrates well with the existing content.

https://github.com/jfmartinz/ResourceHub/issues/359

# Screenshots
image

https://github.com/jfmartinz/ResourceHub/assets/142652964/26d08482-917b-4b65-acec-aef3a569e1f1

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@jfmartinz 
Kindly review the PR and merge adding suitable labels
Thankyou

**Comment by Aditi22Bansal** [comment]
@Kumar-Ankit56 
This is the PR
Kindly review and merge 
Thankyou

**Comment by Aditi22Bansal** [comment]
@Kumar-Ankit56 
@jfmartinz
Kindly review the PR and merge adding suitable labels
Thankyou

**Comment by Aditi22Bansal** [comment]
@Kumar-Ankit56
@jfmartinz
Kindly review the PR and merge adding suitable labels
Thankyou

**Comment by jfmartinz** [comment]
Sorry for the late response, thanks @Aditi22Bansal

**Pull request merged**
