### PR TITLE
Added new books to Computer Architecture

### PR DESCRIPTION
**Pull request by dohinafs**
# Pull Request

## Description
I added links to two new books in the paid books section of Computer Architecture

Closes # 

## Type of change
- [x] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

### CODE REVIEW

**Comment by jfmartinz** [comment]
Resolve the conflcit please, thanks

**Comment by jfmartinz** [comment]
It seems like you have similar changes into this PR #1373. Is this PR and this #1373 the same?

**Comment by dohinafs** [comment]
I have resolved the conflict

**Comment by dohinafs** [comment]
> It seems like you have similar changes into this PR #1373. Is this PR and this #1373 the same?

No, I fixed a broken link in PR #1373 and also added a books section to DSA with relevant links.
In this PR, I added a few more links to an already existing books section for CA.

**Review by jfmartinz — APPROVED** [review]

**Pull request merged**
