### PR TITLE
Add OpenCV Flappy Bird Game

### LINKED ISSUE #184: Flippy Bird Game using Face Detection!
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

If a site crashes the users can be redirected to a page where they can play an interesting flippy bird game through their face detection. When one will Nord their head the bird will go up and down. It will be interesting and I can implement it. 

### Explain your solution

Steps I will be performing: 

1. I will set up a development environment and install the necessary libraries like MediaPipe and a game development framework like Pygame. 

2. I'll use MediaPipe to detect face movements or gestures to control the game, while also implementing the game mechanics such as the bird's movement and obstacles.

3. i’ll Implement the game logic, including collision detection between the bird and the pipes, scoring, and game over conditions.

4. I will be providing feedback to the player based on their face movements. For instance, you could display instructions or feedback on the screen based on how the player is moving their face.

There will be many more tasks I will be implementing here including Refinement, Optimisation, Deployment etc. 

It's a challenging project, but definitely doable with some coding skills and patience! 

### Any alternative approaches/features

_No response_

### Additional Context

Why me?

I am GSSOC'24 Contributor With deep expertise in CNNs and computer vision, I am well-suited for this project. My experience encompasses theoretical understanding and practical application, as demonstrated by presentations and project work. Recently I contributed to a startup where my role centered around the areas of computer vision (image recognition, object detection and pose estimation) and large language models (hallucination mitigation, access control, RAG, fine-tuning, knowledge graphs, dynamic policy enforcement) making me confident in contributing effectively to this endeavor.

Kindly assign me this issue, also I will be doing it from scratch so please add a GSsoC label 3 tag to it.

### PR DESCRIPTION
**Pull request by vishuhere**
`Category - Flippy Bird Game using Face Detection! #184 `  

Closes #184

### CODE REVIEW

**Comment by jfmartinz** [comment]
CAn you demo it or give me the output?

**Comment by vishuhere** [comment]
> CAn you demo it or give me the output?

Sure! Have this output screenshot.

image

image

**Comment by jfmartinz** [comment]
I mean like for example how does this code work on the project? You said:

"If a site crashes the users can be redirected to a page where they can play an interesting flippy bird game through their face detection. When one will Nord their head the bird will go up and down. It will be interesting and I can implement it."

Is it possible to demo it, so I can see?

**Comment by vishuhere** [comment]
You can run the code in Anaconda (coding platform) and can enjoy the game. I hadn't hosted it on a live web server so that I can show you a demo of it because like I told you earlier after your website is deployed you can be able to add this game on your website (you can DM me later and I will do it for you, I will raise another issue for this for that upcoming time). 

In short: The coding part of the game is done and only need to be deployed which is to be done after the completion of your website.

If you have further issues feel free to DM me in future over LinkedIn too I will be happy to help.

**Comment by jfmartinz** [comment]
> You can run the code in Anaconda (coding platform) and can enjoy the game. I hadn't hosted it on a live web server so that I can show you a demo of it because like I told you earlier after your website is deployed you can be able to add this game on your website (you can DM me later and I will do it for you, I will raise another issue for this for that upcoming time).
> 
> In short: The coding part of the game is done and only need to be deployed which is to be done after the completion of your website.
> 
> If you have further issues feel free to DM me in future over LinkedIn too I will be happy to help.

Let's COnnect then:

https://www.linkedin.com/in/jfmartinz/

Thanks

**Comment by jfmartinz** [comment]
> code in Anaconda (coding platform)

We're planning to redesign the site so I can reach out to you once its ready, thanks

**Pull request merged**
