### PR TITLE
Web development - About Page Updated 

### LINKED ISSUE #555: 💡 [FEATURE] - <About Page>
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I want to make the About page.Kindly assign me this @jfm

### Explain your solution

NA
### Any alternative approaches/features

NA

### Additional Context

NA

### PR DESCRIPTION
**Pull request by Ojas-Arora**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

Closes #555 

- 
-
-

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ ] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Comment by jfmartinz** [comment]
CAn iI see the before and afret

**Comment by Ojas-Arora** [comment]
@jfmartinz What are you trying to convey?  I can't understand

**Comment by jfmartinz** [comment]
the result

**Comment by Ojas-Arora** [comment]
Screenshot 2024-06-03 180222
Screenshot 2024-06-03 180329
@jfmartinz Please review it and I think it should be of minimum level 2 issue.

**Comment by jfmartinz** [comment]
fix the conflcit

**Comment by jfmartinz** [comment]
conflict

**Comment by Ojas-Arora** [comment]
@jfmartinz I have fixed all the conflicts. Please review and merge.

**Comment by Ojas-Arora** [comment]
@jfmartinz  Also change this to level 2

**Comment by jfmartinz** [comment]
sure.

**Review by jfmartinz — APPROVED** [review]

**Comment by Ojas-Arora** [comment]
@jfmartinz you have not changed the issue to level2

**Pull request merged**
