### PR TITLE
DBMS (Database) - Added "MySQL" Resources 

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Description

Hey @jfmartinz  I have formatted the folder structure for DBMS(Database) directory and added MySQL resources 

#### Database Folder structure:
image

#### MySQL Resources
image

## Type of change
- [x] Adding a new Resource
- [x] Adding a new Category
- [x] Documentation enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by jfmartinz** [comment]
Check the content in prog language folder, I think someone already add mySQL, did you create new content for mySQL readme?

**Comment by MastanSayyad** [comment]
@jfmartinz Programming languages direcory which is completely about languages and frameworks has resources for **SQL "language"** but in DBMS (Databse) folder which will only be about different databases SQL/NoSQL such as MySQL oracle MongoDB casaandra SQL server etc etc and now I have added resources for **MySQL "Database"**

**Review by jfmartinz — APPROVED** [review]

**Comment by jfmartinz** [comment]
Okay. I see it now.

**Comment by jfmartinz** [comment]
Can you add also complete noSQL? since we have it in this [folder](https://github.com/jfmartinz/ResourceHub/tree/main/Programming%20Languages/SQL). Once youre finished add it into the Database folder for better categorization. Tahnks

**Comment by jfmartinz** [comment]
SQL and we're lacking for noSQL

**Pull request merged**
