### PR TITLE
Added SQL and NoSQL database and removed table

### LINKED ISSUE #226: 💡 [FEATURE] - Adding some more popular databases under README.md file
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I want to contribute to the Readme.md file under DBMS by adding some more popular databases under NoSQL and SQL sections along with a brief description  about them such as Redis ,Oracle and Neo4j. Also would like to add a section differentiating between SQL and NoSQL database which will be helpful for the beginners to understand the difference between the two

### Explain your solution

NA

### Any alternative approaches/features

NA

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SaileePhal**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `DBMS (Database) - SQL and NoSQL database`
- `DBMS (Database) - Removed difference between SQL and NoSQL`

### Fixes Issue
Closes #226 

### Description: 
Added Redis, Oracle and Neo4j databases along with a brief description about each of them. Removed the difference table between SQL and NoSQL database as suggested by the Project Admin/Mentor.
I have also modified the Table of Contents by removing the tag that led to the difference.

### Resource URL: 
Redis : https://redis.io/
Oracle : https://www.oracle.com/in/database/
Neo4j : https://neo4j.com/product/neo4j-graph-database/

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Review by jfmartinz — APPROVED** [review]
Thankjs

**Comment by SaileePhal** [comment]
Sir I guess there has been a small mistake from your side . Sir, I have completed this task and the PR has been successfully merged 
and I feel this should be closed whereas you have assigned this to me again . 
Also sir not only this put other PR's also have been assigned to me where I have already completed the task and PR has been merges successfully .These are a list of them :
1.   https://github.com/jfmartinz/ResourceHub/pull/236#event-12986153016
2    https://github.com/jfmartinz/ResourceHub/pull/254#event-12986243233
3    https://github.com/jfmartinz/ResourceHub/pull/251#event-12986244947
4    https://github.com/jfmartinz/ResourceHub/pull/329#event-12986292461
5    https://github.com/jfmartinz/ResourceHub/pull/326#event-12986305690
6    https://github.com/jfmartinz/ResourceHub/pull/325#event-12986309822
7    https://github.com/jfmartinz/ResourceHub/pull/315#event-12986316568
8    https://github.com/jfmartinz/ResourceHub/pull/406#event-12986356756
9    https://github.com/jfmartinz/ResourceHub/pull/244       (including this one)

Sir is there any changes you wanted me to do?

**Comment by jfmartinz** [comment]
Gssoc requires it. You can check your email for the announcement, I hate to do it but i dont have choice, for your points to be counted in the leaderboard. I hope this clarifies your question

**Comment by SaileePhal** [comment]
Ohh okk sir my bad, sorry was not aware of this at all since this is my first time . 
Thank you so much sir

**Pull request merged**
