### PR TITLE
website-navbar changing issue solved

### LINKED ISSUE #672: 🐞 [BUG] - Navbar changiing behaviour with pages
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

in home,contact,service page navarbar is on full top 
but in about page someone has chnages css of navbar so it is adding paddinf top 
so it not consistent
also in about page navbar does not hav any dark mode toggler
Screenshot (271)_LI

### Expected behavior

navbar always should be fixed
with same size,same margin , same position
also there should be same options in all of the pages

### Steps to reproduce

i will change css and js as well wherever requires

### Additional Context

please assign me this issue 
i will make sure that other thing won't be affected on my changes 
Thanks you

### PR DESCRIPTION
**Pull request by Yashgabani845**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

Closes #672 

### Description: 
i have chnaged mainly css of the about page 
and made same as ther home page 

### Request :
i want to request you about one thing
i saw that css of home page is getting bad after many PRs
someone has remvoed dark mode button  and someone has removed toggle button
so please look at the file changes people are chnaging style of other things for their feature

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@jfmartinz please review it and 
kindly look over my request
if you want then this whole homepage Ui can be given to one person so that no conflict occure

**Comment by Yashgabani845** [comment]
https://github.com/jfmartinz/ResourceHub/assets/127788321/d5001c0a-9a34-4187-be99-5dd86e50d877

@jfmartinz just look at this video this is current situation of white theme 
and the worst part is there is no button of chnaging dark to white or white to dark in home page
it showing to user according to browser chrome shwoing me dark mode and firefox white one 
the main issue is everyone has thier own css of thier forked repo for white mode and people edit according to their view but at the end after merge overall look is getting like this
so i would request you to please look over it and assign white theme css to one person not multiple,
i  will be too happy to work on that 
if you agreed then please tell me i will raise issue on this

**Comment by Yashgabani845** [comment]
@jfmartinz condition of dark theme is very good 
but because of multiple persons working on white theme so ...

**Comment by jfmartinz** [comment]
Can I see your work?  I am trying to enabled the preview in production, so I will see the output easily. Also we're trying to make some unit testing to make sure everything works even after changes of other perople.

**Comment by Yashgabani845** [comment]
Screenshot (355)
Screenshot (356)
sorry for uplaoding late but these are relevant ss for current issue

**Comment by Yashgabani845** [comment]
@jfmartinz please checkout the screenshots of both pages as made both identical

**Comment by jfmartinz** [comment]
What did you do in this PR?

**Comment by jfmartinz** [comment]
Set aside other issue, focus on the issue youre working on, then you can create another one after

**Comment by Yashgabani845** [comment]
@jfmartinz 
navbar behaviour was chaning with pages you told me fix the navbar i have fixed in both of the pages about and home ane metioned ss beofore

**Comment by jfmartinz** [comment]
Haha ,sorry. lot of issues reviewed today, most of them are duplciate, just tired maybe hahah

**Comment by Yashgabani845** [comment]
@jfmartinz  so what should i consider about this PR?

**Pull request closed without merging**
