### PR TITLE
Updated "Programming Language" folder structure and Made Additions in "R programming"

### PR DESCRIPTION
**Pull request by MastanSayyad**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

### Description: 
@jfmartinz  Updated folder structures for Programming Languages and Made additions in R programming.

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [X] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [X] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Review by jfmartinz — CHANGES_REQUESTED** [review]
Things you need to change:
1.  You don't need to add description for the child elements.
For example:
Tutorials Section should have a description but its child should not have any, just describe the overall content of the tutorials section in concise as possible.

For example in [Fundamentals(https://github.com/jfmartinz/ResourceHub/blob/1f91d6cfda6c2140584fdb0e4ec91918f3440610/Programming%20Languages/R/readme.md#fundamentals) is a child of [Tutorials](https://github.com/jfmartinz/ResourceHub/blob/1f91d6cfda6c2140584fdb0e4ec91918f3440610/Programming%20Languages/R/readme.md#tutorials) 

Tutorial should have concise description, no need for the child.

2. You don't need to add new col for 'topic':
image

Instead, you can add it if you want in the description col, up to you. But no need to add topic col in the table.

3. The order of the col should be:
    1. Resource Name (With URL)
    2. Description
    3. Cost (if applicable like books, courses, etc)

4. Remove the [Additional Tips](https://github.com/jfmartinz/ResourceHub/blob/1f91d6cfda6c2140584fdb0e4ec91918f3440610/Programming%20Languages/R/readme.md#additional-tips)

**Comment by jfmartinz** [comment]
Did you create this FOlder?

**Comment by MastanSayyad** [comment]
@jfmartinz  I will make the changes right away

**Comment by MastanSayyad** [comment]
@jfmartinz I think we should keep Topic name column for some tables as they provide much more organized view and remove for those which are completely irrelevant

**Comment by MastanSayyad** [comment]
And No, I did not create R programming folder, I"ve just added some resources and valid roadmap

**Comment by jfmartinz** [comment]
Okay. Thanks

**Comment by MastanSayyad** [comment]
@jfmartinz I have done the required changes

**Comment by jfmartinz** [comment]
> @jfmartinz I think we should keep Topic name column for some tables as they provide much more organized view and remove for those which are completely irrelevant

We need to make some changes to the columns as they are not crucial for our current requirements. Since the data will be displayed on the website in a card format rather than a table, adding new columns like 'topic' and others is unnecessary. 

Also because some of other folders follow this structure.  Just for consistency. 

But I will going to merged this now, thanks

**Comment by MastanSayyad** [comment]
@jfmartinz I've removed topics in it and I got it I will remove it further

**Pull request merged**
