### PR TITLE
Update C programming Notes readme.md

### PR DESCRIPTION
**Pull request by sheetal-81**
# Pull Request
#1095

## Description
Please include a summary of the changes and the related issue.  
Added C programming Notes

Closes # 

## Type of change
- [X] Adding a new Resource
- [X] Adding a new Category
- [X] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [X] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

### CODE REVIEW

**Review by jfmartinz — APPROVED** [review]

**Comment by sheetal-81** [comment]
i wish to add many more notes

**Comment by jfmartinz** [comment]
Sure. But can you compile all those things and then create one PR, just to avoid spams since GSSOC just announced it recently. You can always refer to CONTRIBUTING.md to get an idea in particular area to contribute. Thanks

**Comment by sheetal-81** [comment]
Yes. Even i also want to add all resource at the same time .
but the problem is whenever i am making changes in the readme.md file it shows the preview correctly but my work do no show , give the message like you do not have write access.

**Comment by sheetal-81** [comment]
is this issue came since i fork your repository ?

**Comment by jfmartinz** [comment]
What do you mean? can you explain the issue youre encountering? Is this related to 'Merge Conflict'? Something like this?

image

Definition:

Often, merge conflicts happen when people make different changes to the same line of the same file, or when one person edits a file and another person deletes the same file. You must resolve all merge conflicts before you can merge a pull request on GitHub.

You can read this, to get an idea how to solve the problem. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by jfmartinz** [comment]
If you have more questions, feel free to ask me, and Ill try my best to answer it, I hope this helps, rhanks

**Pull request merged**
