### PR TITLE
Added Error 404 page, along with a Home Page and About Us page for the website

### LINKED ISSUE #134: 🐞 [BUG] - Error 404 Page not found
### Issue Verification

- [X] I have verified that this is a new bug report.

### Describe the bug

If the url is not valid we will be directed to 404 not found page. This will alert the users that they're on the wrong url.

### Expected behavior

A dedicated Error 404 page for when the users click on or search for any wrong url. This will maintain the originality of the website.

### Steps to reproduce

Create a separate Error 404 Page for the users to know that they're visiting a wrong link.

### Additional Context

_No response_

### LINKED ISSUE #139: 💡 [FEATURE] - Website to display all resources
### Idea Contribution

- [X] I have read all the feature request issues.

### Explain feature request

Creating a website to display these resources, trying to provide a better User Experience than navigating a repository.

### Explain your solution

I'll make a simple landing page with a brief description of the project, and then links to 3 pages containing Web Dev, UI/UX and Web3 resources.
Each page will contain cards or tables to display the resources.

### Any alternative approaches/features

Do let me know if you have any specific ideas that you'd like me to implement. Also do mention if you have any specific font, color-scheme or anything in mind. Hope we can work together to create a great website.
[My portfolio website](rahulpandey.co)
[Frontend Mentor Solutions](https://rahul-p19.github.io/frontend-mentor-solutions-rahul/)
Some of the work I've done, do let me know if there's anything you like so that I could implement something similar, or something you dislike so I can avoid it.

### Additional Context

_No response_

### LINKED ISSUE #148: 💡 [FEATURE] - Making a Landing Page
### Idea Contribution

- [X] I have read all the feature request issues.

### Explain feature request

I think we should make a landing page that should be visually appealing but not too fancy and should redirect the user to any of three domains of Web dev, UI/UX or Web3.

### Explain your solution

 We can make nice looking tables for it and can simply attach our resources by grouping them. Then User can be redirected to that area of page in one click. And he can explore the resources there.

### Any alternative approaches/features

_No response_

### Additional Context

It would make the landing page much better and even it can be more easy to spread and understand for newbies.

### PR DESCRIPTION
**Pull request by r7projects-shayan**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Fixes Issue

Fixes #134 
Fixes #148 
Fixes #139 

Closes #134
Closes #148
Closes #139 

### Description: 

Added Error 404-page along with a dedicated Landing Page for the website so that users can easily navigate to the GitHub repository, added About Us page too.

### Screenshots: 

Screenshot 2024-05-15 231643
Screenshot 2024-05-15 231649
Screenshot 2024-05-15 231656
Screenshot 2024-05-15 231709
Screenshot 2024-05-15 231716
Screenshot 2024-05-15 231723
Screenshot 2024-05-15 231734

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. 
- [x] I followed the Code of Conduct

### CODE REVIEW

**Comment by jfmartinz** [comment]
Why didn't you say that you could build the website? I thought you were just going to create the 404 page. I could have assigned it to you, but someone is already working on it. #166.

**Comment by r7projects-shayan** [comment]
@jfmartinz I'm sorry, the error page needed a home page so I built it. If you merge this pull request the person already working maybe able to make changes on top of it. It will reduce the time taken and make it a lot faster.

**Comment by r7projects-shayan** [comment]
@jfmartinz Should I create another pull request with Only the Error Page?

**Comment by jfmartinz** [comment]
> @jfmartinz Should I create another pull request with Only the Error Page?

Yes. If you can. But I like the website you built, maybe after the website is done building, then maybe you can help us make it more better, thanks

**Comment by jfmartinz** [comment]
What if you two #166 work together to create the website and speed it up, what do you think? Hes using HTML CSS JS and API to create the website, and I will give you booth level 3 for it?

**Comment by r7projects-shayan** [comment]
@jfmartinz That sounds like a good idea. So firstly, I'm creating another pull request with only the Error page so this issue gets closed, and then I will change the homepage in html, css, js stack and work with him.

**Comment by jfmartinz** [comment]
Actually the guy said that the website is ready for the development, but I think you could help us for making it better? Maybe Ill c reate simple design and then well see. You can connect with me if you want [here](https://www.linkedin.com/in/jfmartinz/) (linkedin)

**Comment by r7projects-shayan** [comment]
Sure @jfmartinz . I'll see if the website needs improvement after

**Pull request closed without merging**
