### PR TITLE
Added "Java Development" and "Java" Resources

### PR DESCRIPTION
**Pull request by MastanSayyad**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Description: 
Hey @jfmartinz, I have added Complete detailed resources covering the domain of Java development, These resources are designed to address every need that users may have, providing them with all the information and guidance they need.

Additionally, I've also created Java resources within the Programming Languages folder as instructed.
Please take a look and review it.

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [X] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [X] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by jfmartinz** [comment]
These are things that you need to change:
- if you could just combine the two readme file into one, making it more organized. 
- Remove the Author column in the [Books](https://github.com/jfmartinz/ResourceHub/blob/f64528197aa74bef20df1f4670a2d7c30d071de9/Programming%20Languages/Java.md#books) section 
- The Java Development and Java should be in one readme file. Combine the two readme file into one. 
- The structure of the folder
    /Programming Languages
      java.md
      js.md

This is how it should look like especialyl becacuse for deplyoing it in the website. Inside the folder is the md files for these languages like java and js. Btw, I like the Java Development.md It is really comprehensive and almost complete for me.

**Comment by MIpaltan007** [comment]
@jfmartinz Please assign me this. I can provide good resources on this domain. I have previously contributed ML Resources and Web3 Resources to this repository, you can check them.

**Comment by MastanSayyad** [comment]
Thank you for the feedback and the clear instructions @jfmartinz , I'll make the necessary changes. I'm glad to hear you found the Java Development.md comprehensive and useful. I'd be happy to take on additional programming languages and contribute further. I will raise the issues related to them.

**Comment by MastanSayyad** [comment]
Hi @jfmartinz,
I've made all the requested changes.

**Comment by jfmartinz** [comment]
Sure I can do that. Hope you can help me create more content like this but in other language, if you can? Thanks. I really like your PR.

**Comment by MastanSayyad** [comment]
Thank you @jfmartinz You are one of the most active and polite PAs I ever met who not only considers everyone's issues but also guides them with proper instructions. Sure, I would love to help you.

**Pull request merged**
