### PR TITLE
Web development - CSS Portal & Tools

### PR DESCRIPTION
**Pull request by sakshams23**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by sakshams23** [comment]
Done added 4

**Comment by sakshams23** [comment]
Updated Colors and Icons section

**Review by sakshams23 — COMMENTED** [review]
Please check my PR request

**Comment by sakshams23** [comment]
@jfmartinz

**Review by jfmartinz — APPROVED** [review]

**Comment by jfmartinz** [comment]
Looks good. THanks!

**Pull request merged**
