### PR TITLE
Solved #1476- WEB DEVELOPMENT TOOLS

### LINKED ISSUE #1476: Add about web development tools in the web development folder
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

web development tools in the web development folder

### Explain your solution

_No response_

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
# Pull Request

## Description
Please include a summary of the changes and the related issue.  
Added content
Closes #1476 

## Type of change
- [ ] Adding a new Resource
- [x] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@jfmartinz 
Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@jfmartinz 

Kindly review and merge

**Comment by jfmartinz** [comment]
> @jfmartinz
> 
> Kindly review and merge

We have a table inside a front end directory, dont add another readme for this.

**Comment by Aditi22Bansal** [comment]
@jfmartinz 
Its an altogether another part of web dev
Kindly clear

**Comment by Aditi22Bansal** [comment]
@jfmartinz 

Kindly review and merge

**Comment by Aditi22Bansal** [comment]
@jfmartinz 
Kindly review

**Comment by Aditi22Bansal** [comment]
@jfmartinz 
Kindly review and merge 
Kindly tell where I should have my this PR files in your repo

**Pull request closed without merging**
