### PR TITLE
custom cursor added

### LINKED ISSUE #1514: 💡 [FEATURE] - Add custom cursor
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The existing custom cursor is nice but it does not fit with the website and also has few bugs.

https://github.com/jfmartinz/ResourceHub/assets/131477601/aa17a4ce-b7f9-4a8a-9741-baaa8a2a8722

### Explain your solution

I would like to add a custom interactive cursor, like this:

https://github.com/jfmartinz/ResourceHub/assets/131477601/607a6961-938a-41d1-b42d-069ecf87cb92

### Any alternative approaches/features

_No response_

### Additional Context

Would you assign it to me under level2.

### PR DESCRIPTION
**Pull request by chaanakyaaM**
# Pull Request

## Description
Please include a summary of the changes and the related issue.  

I have added the custom cursor and fixed the previous cursor bug.

Closes #1514 

## Type of change
- [ ] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [x] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

## Additional 

Kindly let me if there are any changes to be made.

### CODE REVIEW

**Comment by jfmartinz** [comment]
I need to see hhow it looks.

**Comment by jfmartinz** [comment]
and resolve the conflict

**Comment by chaanakyaaM** [comment]
https://github.com/jfmartinz/ResourceHub/assets/131477601/77649372-34d8-4ba4-bcb5-5388eacf1c3b

**Comment by chaanakyaaM** [comment]
@jfmartinz kindly review this PR.

**Pull request closed without merging**
