### PR TITLE
Added Artificial Intelligence Resource

### PR DESCRIPTION
**Pull request by divyansh-2005**
# Pull Request

Issue: #896 
Feature Request: Artificial Intelligence Resource Addition 

## Description
This pull request includes the following changes:

1. Added a new curated list of resources and projects for learning Artificial Intelligence, covering a wide range of topics and resources such as roadmaps, tools, technologies, courses, books, YouTube channels, playlists, datasets, competitions, communities, GitHub repositories, and project ideas for different skill levels.
2. Organized the content into a structured and easy-to-navigate format, making it accessible for users with varying levels of experience in AI.

## Type of change
- [X] Adding a new Resource
- [X] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

image
image

## Additional 

This update aims to provide a comprehensive guide for individuals interested in Artificial Intelligence, offering a variety of resources to support their learning and development in the field.

### CODE REVIEW

**Comment by divyansh-2005** [comment]
@jfmartinz Please Merge this Pull Request.

**Comment by divyansh-2005** [comment]
I have created a branch "Artificial_Intelligence" and pushed my code. But I am getting "Some checks were not successful".
what is issue with my pull request ?

**Review by jfmartinz — APPROVED** [review]

**Review by jfmartinz — CHANGES_REQUESTED** [review]
You have problem on this one:
image

Ill merged it once you resolved it

**Comment by divyansh-2005** [comment]
I have resolved the problem.

**Pull request merged**
