### PR TITLE
"UI/UX Design - Figma Resources"

### LINKED ISSUE #177: 💡 [FEATURE] - Addition of FIGMA specific content
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

ResourceHub's current Figma resources are limited, failing to reflect Figma's popularity as a mainstream UI/UX design tool.

This lack of in-depth Figma content hinders web developers, particularly those interested in UI/UX design, from fully utilizing ResourceHub's potential. Expanding the Figma section with a wider range of high-quality resources would significantly enhance the platform's value for this user group.

### Explain your solution

I can create a new Figma section within ResourceHub's UI/UX category. This section will feature:

UI/UX Kits & Templates: Pre-designed components and mockups to jumpstart Figma projects.
Open-Source Icons: Extensive libraries of icons for enhanced visual communication.

### Any alternative approaches/features

NA

### Additional Context

NA

### PR DESCRIPTION
**Pull request by Nikhil-1426**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples :

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Fixes Issue

Closes #177 

### Description: 
Created a new section within the UI/UX featuring valuable resources for Figma users where users can explore a range of helpful websites offering free templates, icons, and UI kits.

### Resource URL: 

- https://elements.envato.com/graphic-templates/compatible-with-figma
- https://figmaresource.com/
- https://freebiesui.com/figma-freebies/
- https://dribbble.com/
- https://www.uxcrush.com/
- https://www.getfigit.com/

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [ x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by Nikhil-1426** [comment]
Hi @jfmartinz , I was hoping to hear back from you

**Comment by jfmartinz** [comment]
> Hi @jfmartinz , I was hoping to hear back from you

Sorry for the late reply. Could you please separate these resources and categorize them as follows:

UI/UX Kits & Templates: Pre-designed components and mockups to jumpstart Figma projects.
Open-Source Icons: Extensive libraries of icons for enhanced visual communication.
Create different tables for each category you mentioned. For example, UI/UX Kits & Templates should have its own table, Mockups should have a separate table, and Icons and Libraries should each have their own tables.

**Comment by Nikhil-1426** [comment]
@jfmartinz heyy, i made the changes, suggested by you. Could you please review them ?

**Comment by Nikhil-1426** [comment]
@jfmartinz Heyy, could you please review the changes ?

**Review by jfmartinz — APPROVED** [review]

**Comment by jfmartinz** [comment]
Thanks

**Pull request merged**
