### PR TITLE
Backend Development - Frameworks, Additional Components, APIs

### LINKED ISSUE #150: 💡 [FEATURE] - Resources for the Backend development
### Idea Contribution

- [X] I have read all the feature request issues.

### Explain feature request

The web development is always divided into 2 categories , frontend and backend, I saw in the issues sections that someone is working on the resources for the frontend development but no one is working on the resources for the backend development,
i would like to work on the resources for the backend development including frameworks, databases, APIs and more.

### Explain your solution

I would link all the authentic and helpful links on backend development included with the description.

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by chaanakyaaM**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Fixes Issue

Closes #150 

### Description: 

Resources (tutorial links) are added for Frameworks, Additional Components and APIs

### Resource URL: 

```
<table width="100%">
    <tr>
        <th>Resource Name</th>
        <th>Description</th>
    </tr>
    <tr>
        <td><a href="https://nodejs.org/en/learn/getting-started/introduction-to-nodejs">Node.js</a></td>
        <td>The Node.js Documentation covers topics such as file system operations, networking, streams, event handling,
            and more. It includes detailed explanations, code examples, and usage guidelines for each API and module,
            making it easy for developers to understand and implement Node.js features in their applications.</td>
    </tr>
    <tr>
        <td><a href="https://www.tutorialspoint.com/expressjs/index.html">Express.js</a></td>
        <td>Tutorialspoint's Express.js tutorial is a valuable resource for anyone looking to learn Express.js, a popular web application framework for Node.js. This tutorial provides a comprehensive overview of Express.js, covering everything from basic concepts to advanced topics.</td>
    </tr>
    <tr>
        <td><a href="https://docs.djangoproject.com/en/5.0/intro/tutorial01/">Django</a></td>
        <td>Django introductory tutorial from the official documentation serves as an excellent starting point for individuals looking to learn Django. Whether you're a beginner or an experienced developer, this resource provides the guidance and knowledge needed to kickstart your journey into Django web development.</td>
    </tr>
    <tr>
        <td><a href="https://flask.palletsprojects.com/en/3.0.x/">Flask</a></td>
        <td>Flask documentation is more than just a reference manual, it's a gateway to mastery in Backend development with Python. Whether you're a noob exploring Flask's possibilities or a seasoned developer seeking to optimize your workflow, Flask documentation equips you with the knowledge and resources to excel in your endeavors.</td>
    </tr>
    <tr>
        <td><a href="https://www.tutorialspoint.com/restful/index.html">RESTful APIs</a></td>
        <td>The Tutorialspoint's RESTful tutorial provides a comprehensive introduction to RESTful principles, explaining key concepts such as resources, URIs, HTTP methods, and representations. It also provides the foundational knowledge which is essential for building scalable and interoperable web services.</td>
    </tr>
    <tr>
        <td><a href="https://www.tutorialspoint.com/graphql/index.html">GraphQL</a></td>
        <td>The Tutorialspoint's GraphQL tutorial is an excellent resource for individuals looking to learn about GraphQL, a query language for APIs.Its easy for learners to progress through the material at their own pace. It starts with the basics and gradually introduces more advanced topics, ensuring that learners build a solid understanding of GraphQL concepts.</td>
    </tr>
    <tr>
        <td><a href="https://www.tutorialspoint.com/oauth2.0/index.html">OAuth 2.0</a></td>
        <td>This tutorial provides a comprehensive overview of OAuth 2.0, covering its core concepts, flows, and components. This foundational knowledge is essential for developers looking to integrate OAuth 2.0 into their applications securely.</td>
    </tr>
    <tr>
        <td><a href="https://www.docker.com/101-tutorial/">Docker</a></td>
        <td>The Docker's "101 Tutorial" provides a gentle introduction to containerization concepts, explaining how Docker enables developers to package applications and their dependencies into lightweight, portable containers. This foundational knowledge is crucial for understanding Docker's role in modern software development.</td>
    </tr>
    <tr>
        <td><a href="https://www.jenkins.io/doc/tutorials/">Jenkins</a></td>
        <td> Jenkins' official documentation website, these tutorials provide accurate and up-to-date information directly from the creators of Jenkins. Users can rely on the authenticity and reliability of the content.</td>
    </tr>
    <tr>
        <td><a href="https://aws.amazon.com/documentation-overview/">AWS</a></td>
        <td>The AWS Documentation is a comprehensive resource hub for individuals and organizations utilizing Amazon Web Services (AWS) cloud computing services, this documentation provides the guidance, reference material, and support needed to effectively leverage AWS for your projects and initiatives.</td>
    </tr>
    <tr>
        <td><a
                href="https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Introduction">API</a>
        </td>
        <td> Mozilla's developer documentation on client-side web APIs for JavaScript is a best resource for individuals looking to enhance their understanding of web development. The content is curated and maintained by a community of experts, ensuring accuracy and relevance.
        </td>
    </tr>
</table>
```
(https://nodejs.org/en/learn/getting-started/introduction-to-nodejs)
(https://www.tutorialspoint.com/expressjs/index.htm)
(https://docs.djangoproject.com/en/5.0/intro/tutorial01/)
(https://flask.palletsprojects.com/en/3.0.x/)
(https://www.tutorialspoint.com/restful/index.htm)
(https://www.tutorialspoint.com/graphql/index.htm)
(https://www.tutorialspoint.com/oauth2.0/index.htm)
(https://www.docker.com/101-tutorial/)
(https://www.jenkins.io/doc/tutorials/)
(https://aws.amazon.com/documentation-overview/)
(https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Introduction)

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by jfmartinz** [comment]
Can you please resolve the conflict and then merged this after the change @chaanakyaaM

**Comment by jfmartinz** [comment]
You can read and check this [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line#competing-line-change-merge-conflicts) if you need help.

**Comment by chaanakyaaM** [comment]
Done sir !

**Comment by jfmartinz** [comment]
Yay

**Pull request merged**
