### PR TITLE
corrected service button 

### PR DESCRIPTION
**Pull request by aindrelasaha**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

Closes #10

image

- 
-
-

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Comment by jfmartinz** [comment]
Can you please solve the conlict

**Comment by aindrelasaha** [comment]
> Can you please solve the conlict

sure sir

**Comment by aindrelasaha** [comment]
image
sir, there is no conflict from my side, its probably an authorization error from Your side for deploying to vercel. most prolly u changed your hosting platform to vercel which is causing this conflict.


on successful merging, vercel can deploy it, and the error will get resolved automatically, it’s more of an error from your side

thank you sir
@jfmartinz

**Comment by jfmartinz** [comment]
No, I mean its conflicting since someone also change the content that you're chaning. Merged conflict. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

**Pull request closed without merging**
