### PR TITLE
Added Machine Learning Courses

### LINKED ISSUE #287: 💡[Feature] : Add Resources of Machine Learning
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I would like to add an useful resource which would help people get into Machine Learning Algorithms as the market is developing towards AI/ML. 

please assign this issue to me under gssoc24?

### Explain your solution

Firstly, we give the roadmap to students
then, Videos acc to the roadmap 
and then practice videos with the different projects for learning how to make a ML Algoritghm

### PR DESCRIPTION
**Pull request by Priyanshu2743**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Machine Learning`

### Fixes Issue

Closes #287 

### Description: 

Created Machine Learning Readme.md File
Added Resources under Machine Learning Readme.md File

### Resource URL: 

-- Lenear Algebra (https://www.youtube.com/playlist?list=PLRDl2inPrWQW1QSWhBU0ki-jq_uElkh2a)
-- Probability And Statistics (https://www.youtube.com/playlist?list=PLPzjifo9TUNX8UKgRBKgMGF5nYB_uEe0h)
-- Python (https://www.youtube.com/watch?v=bY__YW-xknU&list=PLfFghEzKVmjsNtIRwErklMAN8nJmebB0I)
-- Core Machine Learning (ML) Algorithms (https://www.youtube.com/watch?v=bY__YW-xknU&list=PLfFghEzKVmjsNtIRwErklMAN8nJmebB0I)
-- Deployment of model in Machine Learning (https://www.youtube.com/watch?v=bjsJOl8gz5k)

Projects links  --
-- Diabetes Prediction (https://www.youtube.com/watch?v=xUE7SjVx9bQ&feature=youtu.be)
-- Movie Recommendation System (https://www.youtube.com/watch?v=1xtrIEwY_zY&feature=youtu.be)
-- Credit Card Fraud Detection (https://www.youtube.com/watch?v=NCgjcHLFNDg)
-- Production Grade Project (https://www.youtube.com/watch?v=dPmH3G9NQtY&feature=youtu.be)
-- Cancer Detection Using Deep Learning (https://www.youtube.com/watch?v=UQAKwWUYnuI&feature=youtu.be)

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by jfmartinz** [comment]
Maybe you could add those resources into this folder:

https://github.com/jfmartinz/ResourceHub/tree/main/Machine%20learning

**Comment by Priyanshu2743** [comment]
Ok I Will

**Comment by Priyanshu2743** [comment]
Kindly Add the label of gssoc and level 
It helps me a lot

**Comment by jfmartinz** [comment]
i mean just add the resources that you have that doesnt exist on the current resourcesi n machine learning category

**Pull request closed without merging**
