### PR TITLE
Cyber security - Communites

### PR DESCRIPTION
**Pull request by chaanakyaaM**
# Pull Request

## Description
Please include a summary of the changes and the related issue.  

I have added other useful reddit communities under cyber security.

Closes # 

## Type of change
- [x] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

### CODE REVIEW

**Comment by jfmartinz** [comment]
Hey @chaanakyaaM, I think you should focus on other repos in the project if you want to contribute further since there is a latest announcment about max levels and rules that PAs need to follow. Check this [link](https://github.com/GSSoC24/Contributor/blob/main/gssoc-guidelines/readme.md)

**Comment by chaanakyaaM** [comment]
So shall i create a issue before sending you the PR?

**Comment by chaanakyaaM** [comment]
image

**Comment by jfmartinz** [comment]
No. What I mean is GSSOC is complaining about spam PRs, if you want to add new resources, just compile everything you have and raise one PR instead of keep creating PR with the same issue which is 'Adding resource'. To avoid it, just compile evey resources and raise one PR

**Comment by jfmartinz** [comment]
You can instead work on other areas of the project. Avoid creating PR for adding new resources since you made a lot of contributions aabout htat

**Comment by chaanakyaaM** [comment]
Other areas like what kind, and also there are many incomplete resources in different categories.

**Pull request closed without merging**
