### PR TITLE
Programming Languages - Added "GraphQL" Complete Resources

### LINKED ISSUE #1055: ➕ [RESOURCE] - Programming Language "GraphQL" Complete Resources
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

hey @jfmartinz, 
I would like to add "GraphQL" Resources in Programming Language.

- Introduction to GraphQL
- GraphQL Basics
- Core Concepts
- Defining a Schema
- Advanced GraphQL Concepts
- GraphQL Clients
- Authentication and Authorization
- Validation
- Execution
- Books
- Courses
- Youtube Tutorials

Could you please assign me this under GSSOC'24?

### Provide the URLs of the resources you are adding

_No response_

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @jfmartinz,
issue closes #1055 

## Description
Added Complete GraphQL resources 

image

## Type of change
- [x] Adding a new Resource
- [x] Adding a new Category
- [x] Documentation enhancement or fixes
- [x] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

@jfmartinz, Please take a look. 
Also Please add the levels.

### CODE REVIEW

**Comment by aslams2020** [comment]
@jfmartinz

**Review by jfmartinz — CHANGES_REQUESTED** [review]
Add this resource file into [this](https://github.com/jfmartinz/ResourceHub/tree/main/DBMS%20(Database))

**Comment by aslams2020** [comment]
@jfmartinz, I have Done the changes. Please take a look.

**Comment by aslams2020** [comment]
@jfmartinz

**Review by jfmartinz — APPROVED** [review]
LGTM

**Pull request merged**
