### PR TITLE
Added NoSQL to database

### LINKED ISSUE #1224: 💡 [FEATURE] - <title>Adding NoSQL Resource in DBMS
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

_No response_

### Explain your solution

_No response_

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SadafKausar2025**
# Pull Request 

## Description
Please include a summary of the changes and the related issue.  

Closes #1224

## Type of change
- [x] Adding a new Resource
- [x] Adding a new Category
- [x] Documentation enhancement or fixes
- [x] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @jfmartinz 
can you please review this PR and merge it ?

**Comment by SadafKausar2025** [comment]
hello @jfmartinz 
please approved this PR and review this

**Review by jfmartinz — COMMENTED** [review]
Please read [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md), your format is incorrect. also you need to moved it into this [folder](https://github.com/jfmartinz/ResourceHub/tree/main/DBMS%20(Database))

**Comment by SadafKausar2025** [comment]
hello @jfmartinz 
please also merge it

> Please read [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md), your format is incorrect. also you need to moved it into this [folder](https://github.com/jfmartinz/ResourceHub/tree/main/DBMS%20(Database))

ok

**Comment by jfmartinz** [comment]
I see that this is dupicate issue. This is issue was assigned to someone else before you. Ill close this issue, i mean PR

**Pull request closed without merging**
