### PR TITLE
 Added search bar and separate programing language folder

### PR DESCRIPTION
**Pull request by pandeyji711**
@jfmartinz please name every resourse as readme.md so that it can fetch correctly

### CODE REVIEW

**Comment by pandeyji711** [comment]
mark this Gssoc24

**Comment by jfmartinz** [comment]
Can you create a folder like for example:
 /Programming Languages 
   /Java
    readme.md
To make it look organized and easy to find

**Comment by pandeyji711** [comment]
ok i tried

**Comment by pandeyji711** [comment]
Hi @jfmartinz,

I recommend organizing each resource file separately based on the programming language (e.g., Java, C, etc.). This approach will make your website more attractive and give the impression of having abundant content. Additionally, I’ve added a search bar to the page, allowing users to easily access the resources they need.

**Comment by pandeyji711** [comment]
@jfmartinz  **Please review and mark it level 2 please** 
https://github.com/jfmartinz/ResourceHub/assets/154527778/08847fe1-4ad5-42f4-adf9-0213d1682484

**Comment by jfmartinz** [comment]
Nice.

**Comment by jfmartinz** [comment]
Bro, cant we add it on the programming languages folder to organize it?

**Pull request merged**
