### PR TITLE
added service page

### PR DESCRIPTION
**Pull request by aindrelasaha**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

Closes #10

I have provided the new service page which will somewhat look like this
image
In my next issue I want to bring those resources in the service page

- 
-
-

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [ x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Comment by aindrelasaha** [comment]
@jfmartinz could you please look in to the PR sir 
then I could proceed to the next step that is arranging the resource page in service

**Comment by jfmartinz** [comment]
thats good.

**Comment by aindrelasaha** [comment]
So  sir would you add the PR or I shall wait to do the next issue that is redirecting the service page to here👇🏼
image

**Comment by jfmartinz** [comment]
Sorry. No need to add anaaothe page for servrice. just add it anywhere from the website

**Comment by aindrelasaha** [comment]
ok si @jfmartinz

**Pull request closed without merging**
