### PR TITLE
Dark mode content not visible issue solved

### LINKED ISSUE #784: 🐞 [BUG] - <issue 3 : dark mode content not visible>
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

cark mode "table of content " not visible 

Screenshot 2024-06-03 073659
Screenshot 2024-06-03 073706

### Expected behavior

it should be visible

### Steps to reproduce

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Vipullakum007**
Closes #784 

### Description: 

Before

After

Screenshot (637)
Screenshot (638)

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Comment by Vipullakum007** [comment]
hey @jfmartinz , please review it

**Comment by jfmartinz** [comment]
There is an conflict

**Comment by Vipullakum007** [comment]
hey  @jfmartinz , i have resolved conflicts you can review it

**Comment by Vipullakum007** [comment]
hey @jfmartinz , you will not merge it so that it it not on leaderboard please check it

**Comment by jfmartinz** [comment]
We're going to redesign this, so I will close this PR for now

**Pull request closed without merging**
