### PR TITLE
UI/UX Design & Communities

### PR DESCRIPTION
**Pull request by renunegii**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Description: 
Updated: UI/UX Design - Communities section, Designer Hangout resource was not working properly in place UXPA an international UX designers community link added.

### Resource URL: 
https://www.linkedin.com/groups/717/

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Review by jfmartinz — APPROVED** [review]

**Comment by jfmartinz** [comment]
Please solve the conflict, thanks

**Review by renunegii — COMMENTED** [review]
Not working link of Designer Hangout has been removed and another resource is added in place of it.

**Comment by renunegii** [comment]
@jfmartinz as I do not have access to merge this PR kindly do this from your side.
I'm a beginner GSSOC contributor if I have missed anything let me know, please.

Screenshot 2024-05-19 211826

**Comment by jfmartinz** [comment]
Hey @renunegii, you can check and read [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to get an idea on how to solve the conflict. If you need help and assistance let me know

**Comment by renunegii** [comment]
@jfmartinz it is showing that "only those with write access can merge pull requests"
And I guess that's why the resolve conflicts button is deactivated for me!
below is the screenshot of the same
image

**Review by jfmartinz — APPROVED** [review]
Thanks, now I can merged.

**Comment by renunegii** [comment]
Thank you for helping

**Pull request merged**
