### PR TITLE
Added back to home button in resource section for better navigation

### LINKED ISSUE #1408: 💡 [FEATURE] - <title>Adding a home button at each resource page at exploring resources
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

After exploring a resource if the user wish to see or explore other resources it comes difficult for him to navigate back to the homepage to see other resources as there is no such button provided that redirects to the home after seeing each page.

### Explain your solution

I would like to add a button on each resource page to navigate to the homepage after exploring a particular resource .
It will become user friendly and will also look professional.

### Any alternative approaches/features

_No response_

### Additional Context

Please assign me this issue under gssoc . I assure that i will start working on it immediately.

### PR DESCRIPTION
**Pull request by shraddhha**
# Pull Request
I have added a back to home button in each resource page for better user experience and better navigation.
## Description
User can be engaged while using the app if there is easy use of the app . So i have added a back to home button in each resource page and also in the feedback form so the user if a user wish to switch from one particular section to another he would be easily able to do that.
I have also ensured that the button correctly matches with the UI of the page.

Closes #1408 

## Type of change
- [ ] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [x] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Screenshot 2024-06-23 160003
Screenshot 2024-06-23 160028

### CODE REVIEW

**Comment by jfmartinz** [comment]
No need to add back btn in the feedback form, we have that already:

image

What I mean is refer to the feedback form page to see how back btn works.

**Comment by jfmartinz** [comment]
You can notice the left arrow button. This is what you need to implement to other resources

**Comment by shraddhha** [comment]
Ok  I understood. Sorry for the confusion . Now shall I only   remove the button added in the feedback form or should I remove the button added in the resource page also and add arrow there?

**Comment by jfmartinz** [comment]
> Ok I understood. Sorry for the confusion . Now shall I only remove the button added in the feedback form or should I remove the button added in the resource page also and add arrow there?

No worries. Remove the btns 'back to home' annd just add a left arrow button that will directs to the homepage

**Comment by jfmartinz** [comment]
I hope this make sense, if you have more question then feel free to ask, thanks

**Pull request closed without merging**
