### PR TITLE
fixed css in mobile view #1245

### LINKED ISSUE #1245: 🐞 [BUG] - CSS of page in mobile view is not proper
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

image

css of web page is not proper i would like to fix it

### Expected behavior

_No response_

### Steps to reproduce

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dhairyagothi**
# Pull Request
#1245  solved
## Description
fixed CSS in mobile view 

https://github.com/jfmartinz/ResourceHub/assets/14298#1245 0d37553d-b0d6-4891-bd72-5eebbe31b021

Closes #1245

## Type of change
- [ ] Adding a new Resource
- [ ] Adding a new Category
- [X] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [X] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

### CODE REVIEW

**Comment by dhairyagothi** [comment]
please merge it with gssoc label @jfmartinz

**Comment by jfmartinz** [comment]
Please resolve the conflict and also give me  mp4

**Comment by dhairyagothi** [comment]
> Please resolve the conflict and also give me mp4

how can you assign a PR created by me to someone else @jfmartinz

**Comment by dhairyagothi** [comment]
Assign this PR to me @jfmartinz

**Comment by jfmartinz** [comment]
Resolve the conflict.

**Comment by jfmartinz** [comment]
Also provide the output, we dont have preview yet

**Comment by dhairyagothi** [comment]
@jfmartinz check it now done 


https://github.com/jfmartinz/ResourceHub/assets/142989448/38fbcab5-2d42-45a0-9af1-fd2e8ebd259d

**Comment by dhairyagothi** [comment]
@jfmartinz please merge PR

**Pull request merged**
