### PR TITLE
Feature- Modify readme 

### PR DESCRIPTION
**Pull request by sau-mili**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Description: 

added open source , devops link to read me
added more resource names to read me

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x ] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by sau-mili** [comment]
@jfmartinz please check

**Review by jfmartinz — APPROVED** [review]

**Comment by sau-mili** [comment]
Can you please add GSSOC and Level tags, since I am a GSSOC Contributor?

**Comment by jfmartinz** [comment]
Only in the issue. I added it already.

**Comment by jfmartinz** [comment]
It will work

**Comment by sau-mili** [comment]
Okay, Thanks.. I am a beginner so I was a bit confused about the consideration. Sorry for the inconvenience.

**Comment by jfmartinz** [comment]
> Okay, Thanks.. I am a beginner so I was a bit confused about the consideration. Sorry for the inconvenience.

Hey, no worries :)

**Pull request merged**
