### PR TITLE
done #1184

### LINKED ISSUE #1184: 💡 [FEATURE] - adding hover effect to links.
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

_No response_

### Explain your solution

_No response_

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dnyandeepchute**
# Pull Request

## Description
Please include a summary of the changes and the related issue.  

Closes #1184

## Type of change
- [ ] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [x] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.
Screenshot 2024-06-17 124031

### CODE REVIEW

**Comment by jfmartinz** [comment]
Just reduce the opacity of the links a little bit but not too much.

**Comment by jfmartinz** [comment]
Can I see the result?

**Comment by jfmartinz** [comment]
I mean any screenshot when hovered.

**Comment by dnyandeepchute** [comment]
@jfmartinz please check now, thank you.

**Comment by jfmartinz** [comment]
Provide the screenshot, we dont have preview it, thans

**Comment by dnyandeepchute** [comment]
Screenshot 2024-06-19 111055

**Pull request merged**
