### PR TITLE
Added Chrome Extensions Tutorial

### LINKED ISSUE #842: 💡ADD - How to make Chrome Extensions Playlist
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I want to add a playlist on "How to make Chrome Extensions" using JavaScript

### Explain your solution

_No response_

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ThisIsSahaj**
`Web development - Chrome Extensions Tutorial & Tutorials`

## Description
I have added a comprehensive tutorial playlist on How To Build Chrome Extensions using JavaScript.

Closes #842 

## Type of change
- [x] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

image

### CODE REVIEW

**Comment by jfmartinz** [comment]
What is this resourrce about? You added it in the Tutorial Section. Maybe you can it to the Youtube Playlist or Projects instead of tutorial?

**Comment by ThisIsSahaj** [comment]
@jfmartinz Added it to the Youtube Playlist section, kindly review

**Comment by ThisIsSahaj** [comment]
@jfmartinz @sanjay-kv please review, it's already been 3 days

**Review by jfmartinz — APPROVED** [review]
LGTM

**Pull request merged**
