### PR TITLE
Web development - Table categorized #70

### PR DESCRIPTION
**Pull request by ayushsgithub**
### Fixes Issue
Closes: #70 

### Description: 
Categorize the resources in tutorials section into different section: Front End, Back End, and Full Stack Development for improved user navigation and added h4 for headings

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ ] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Review by jfmartinz — APPROVED** [review]
Thanks!

**Comment by ayushsgithub** [comment]
Thanks @jfmartinz

**Comment by ayushsgithub** [comment]
Hey @jfmartinz, can you please add the hacktoberfest label as well

**Comment by jfmartinz** [comment]
> Hey @jfmartinz, can you please add the hacktoberfest label as well

Done. Thanks!

**Pull request merged**
