### PR TITLE
Two-extensions added

### LINKED ISSUE #1064: ➕ [RESOURCE] - Adding the project for Useful Extensions for Web Developers
### Idea Contribution

- [X] I have read all the resource request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Where do you want to add the resource? Specify the category and section.

I want to add important useful Chrome Extesions for webdeveloper like:
1.WhatFonts : For finding the style and all information related to fonts for styling by just hovering on the text
2.Pesticides : For finding out the layout for websites with easiness by hovering on design provided.

### Provide the URLs of the resources you are adding

_No response_

### Any alternative approaches/features

https://github.com/chengyin/WhatFont-Bookmarklet
https://github.com/paulmolluzzo/pesticide_for_chrome

### Additional Context

_No response_

### Code of Conduct

- [X] I follow the [CONTRIBUTING GUIDELINE](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Maheshwari-Love**
# Pull Request

## Description
I added important Chrome Extensions for web developers like:
1.WhatFonts : For finding the style and all information related to fonts for styling by just hovering on the text
2.Pesticides : For finding out the layout for websites with easiness by hovering on design provided.

Closes #1064 

## Type of change
- [x] Adding a new Resource
- [x] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

## Screenshots (if appropriate):
image
image

### CODE REVIEW

**Comment by Maheshwari-Love** [comment]
@jfmartinz Please review the PR , and add labels

**Comment by jfmartinz** [comment]
Did you read [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)? Please read it, you should add those as a URL aand provide description for each resurce.

**Comment by Maheshwari-Love** [comment]
> Did you read [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)? Please read it, you should add those as a URL aand provide description for each resurce.

added the URL for extensions

**Review by jfmartinz — APPROVED** [review]
Thanks

**Pull request merged**
