### PR TITLE
Scroll Bar update

### LINKED ISSUE #573: 💡 [FEATURE] - Scroll Bar
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

The scroll bar in website has default styling which does not match the theme of the website and degrades the UI.
Screen Shot 2024-05-29 at 8 51 12 PM

### Explain your solution

Enhance scroll bar. Changing its colour according to the website theme. Add visibility only when scrolling and disabling after the page is still (while user is not scrolling and stops at particular section). 

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by hars-21**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

Scroll Bar Styling and functioning updated

Closes #573 

### Description: 
Successfully changed the styling of the scrollbar according to the website theme.
Now scrollbar only displayed when user is scrolling 
The background of scrollbar is changed to transparent so the overall UI of the website doesn't get disturb.

Screen Shot 2024-05-30 at 9 21 22 PM

### Checklist:

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.

### CODE REVIEW

**Comment by jfmartinz** [comment]
Please give me the mp4, thanks

**Comment by hars-21** [comment]
https://github.com/jfmartinz/ResourceHub/assets/144909381/d5b9fd16-6517-48a7-91b7-e100f8d2c21a

This is the updated scroll bar

**Comment by hars-21** [comment]
@jfmartinz Please review. Thanks!

**Comment by jfmartinz** [comment]
Cool. Solve the conflict

**Comment by hars-21** [comment]
done

**Pull request merged**
