### PR TITLE
Programming Languages - "TypeScript Resources"

### PR DESCRIPTION
**Pull request by MastanSayyad**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

### Description: 
Hey @jfmartinz I have added the typescript resources in programming languages, as your instructed format (Topic Excluded)
please take a look and let me know, hope it helps Thank You!!

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [X] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [X] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Review by jfmartinz — APPROVED** [review]
Thanks

**Comment by MastanSayyad** [comment]
@jfmartinz I will make the changes in folders like java, javascript, c/c++ with this format of yours by removing unnecessary topic column, is that okay?

**Comment by jfmartinz** [comment]
Yes, you can create the PR right away

**Comment by jfmartinz** [comment]
Let me mention the mistakes of formatting:

1. The order of the cols should be
  1. Resource name (With the URL)
  2. Description

Some of them does not follow this, example:
 
image
image
image

2. Some of the table does not contain description. Only the parent, the child elements should not have any description.

For example:
[Tutorials](https://github.com/jfmartinz/ResourceHub/tree/main/Programming%20Languages/Java#tutorials) in Java should have description but the child should not have description, for example [Fundamentals](https://github.com/jfmartinz/ResourceHub/tree/main/Programming%20Languages/Java#fundamentals), [OOP](https://github.com/jfmartinz/ResourceHub/tree/main/Programming%20Languages/Java#object-oriented-programming-oop) should not have any description, you should add it on the parent which is tutorial and you're going to describe the section (tutorial) what its about.

**Comment by MastanSayyad** [comment]
Got it @jfmartinz Thank you for the instructions.

**Pull request merged**
