### PR TITLE
3 Resources Added Updated

### PR DESCRIPTION
**Pull request by sakshams23**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [ ] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ ] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by sakshams23** [comment]
@jfmartinz I made the following Changes you proposed.

**Comment by sakshams23** [comment]
Kindly merge it with Hacktoberfest accepted label.

**Comment by sakshams23** [comment]
I also added 2 resources in interview section too.

**Review by jfmartinz — APPROVED** [review]
Looks good @sakshams23! Thanks!

**Pull request merged**
