### PR TITLE
Web Development - Added Games #40

### PR DESCRIPTION
**Pull request by Dev-Abhay01**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

Please follow these steps to create the PR title correctly:

> - Replace "Category" with the relevant category, such as **Web Development** or **UI & UX Design**.
> - Replace "Resource Name & Section" with the specific name of the resource and the relevant section where it belongs. For instance, you could use something like **CSS Portal & Tools** or **Leetcode & Challenges**.

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [ ] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ ] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by jfmartinz** [comment]
Hello @Dev-Abhay01 you removed some of the games that are listen on the section. Please don't remove or edit the existing resources listed and if you have any issues with them. You can raise an issue and discuss about it.

**Review by jfmartinz — CHANGES_REQUESTED** [review]
I think these resources is suitable for challenges section. We have a challenges section, replace them in the appropriate section. Once youre done I will merged this pr. Thank you

The resources that you need to move in the challenges section:
- HackerRank
- Exercism
- Project Euler
- LeetCode
- TopCoder
- Kaggle
- Advent of Code

These resources is approriate for challenges section.

**Comment by Dev-Abhay01** [comment]
i have made changes as you said please review it..

**Review by jfmartinz — COMMENTED** [review]
@Dev-Abhay01 

Problems in these pr before I merged it:
1. You accidently remove the other resources that existed in the table section 'games'
- Flexbox defense
- Flexbox froggy
- Grid garden
-  Code monkey
- CodinGame
- RoboCode
- CSS diner (Exist already, you should remove your CSS diner, the one you added)

2. You added a new td in the table which is wrong. This how adding a resource would look like:
image

Read [contributing.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)

youre changes are getting better, if you want make another branch and make the changes based on the guidelines for this project. Let me know if you have questions Thanks

**Pull request closed without merging**
