### PR TITLE
Add URL Shortner

### LINKED ISSUE #299: ADD URL SHORTNER
in this repo i want to add **### url shortner** 
can i add this

### PR DESCRIPTION
**Pull request by kartikmehta18**
- `Web development -  HTML,CSS, JAVASCRIPT`

Closes #299

### Checklist:

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by jfmartinz** [comment]
Can you instead provide the actual tutorial or guide on how to create that. Dont ad your personal projects, you can  check some resources under Projects to get an idea. For example:

https://www.geeksforgeeks.org/how-to-create-todo-app-using-html-css-js-and-bootstrap/

**Comment by kartikmehta18** [comment]
> Can you instead provide the actual tutorial or guide on how to create that. Dont ad your personal projects, you can check some resources under Projects to get an idea. For example:
> 
> https://www.geeksforgeeks.org/how-to-create-todo-app-using-html-css-js-and-bootstrap/

I got it  so can I add YouTube channel link

**Comment by jfmartinz** [comment]
Yes

**Comment by jfmartinz** [comment]
Blogs, Github, etc

**Comment by kartikmehta18** [comment]
> Yes

https://github.com/jfmartinz/ResourceHub/pull/394#
sir please review this i added tutorial link

**Review by jfmartinz — APPROVED** [review]
Thanks @kartikmehta18

**Pull request merged**
