### PR TITLE
Designed Dedicated "How To Contribute" Webpage To The Website

### LINKED ISSUE #1308: 💡 Design Dedicated "How To Contribute" Webpage To The Website
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hey @jfmartinz 

The current "How to Contribute" link on the website redirects to the GitHub repository directly to the CONTRIBUTING.md file. 

image

To provide a better user experience, a dedicated web page explaining how to contribute to the project should be designed and integrated into the website

### Explain your solution

- **For Example Like This**

image

This page will provide detailed instructions and guidelines on how users can contribute to the project, making it easier for new contributors to get started.

### Any alternative approaches/features

_No response_

### Additional Context

Could you please assign this issue to me under GSSOC24 ?

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
## Description
Hey @jfmartinz  issue closes #1308 

I have Designed Dedicated "How To Contribute" Webpage To The Website
The changes i have made are : 
-  Created dedicated How to Contribute page which contain contributing guidelines from contributing.md file
- Added Fevicon to the page 
- Added Footer 
- Added back to home navigation to title of website
- Integrated back to top button 
- Integrated scroll-down progress bar 

https://github.com/jfmartinz/ResourceHub/assets/163530398/29dc9ad9-afc3-4064-9e75-9218543d26c6

## Type of change

- [X] Website enhancement or fixes

## Checklist:
- [X] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by jfmartinz** [comment]
Can you also please add a 'back' button that once clicked goes back to the home page? after that Ill merged your PR thanks

**Comment by jfmartinz** [comment]
You can check feedback page to get an idea what I mean, thanks

**Comment by RadhikaMalpani1702** [comment]
Hey @jfmartinz 

Added the back button to navigate to the home page

image

**Comment by jfmartinz** [comment]
thanksl

**Pull request merged**
