### PR TITLE
Auto-Commenting Feature for PR Raised

### PR DESCRIPTION
**Pull request by Rajneeshkarya**
**Issue Fixed**

Auto-Commenting Feature for PR Raised [#141](https://github.com/jfmartinz/ResourceHub/issues/141) 

**Description**

This pull request introduces a new GitHub Actions workflow that automatically comments on new and updated pull requests. This feature aims to streamline the contribution process by providing contributors with immediate feedback and guidance upon creating or updating their pull requests.

**Screenshot:**

Screenshot_2024-05-14_20_28_10(1)

Checklist:

Before submitting your pull request, ensure that you have completed the following tasks:

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.

- [x] I have tested the functionality of the feature before making the pull request.

### CODE REVIEW

**Comment by jfmartinz** [comment]
I will merged it for now, but I need to add secret, but I dont know what to put:

image

**Comment by Rajneeshkarya** [comment]
Hi @jfmartinz,

I think now there is no need to add **GITHUB_TOKEN** manually, the GitHub actions workflow will automatically provide the Token.

**Comment by jfmartinz** [comment]
Uh yes. What do you think is the problem, I am currently trying to fix it.

**Comment by Rajneeshkarya** [comment]
The problem was in the authorization of the token, then I used the curl command to authorize the **GITHUB_TOKEN** to generate a comment. see the example below

curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN"

**Comment by Rajneeshkarya** [comment]
Could you tell me that for issue #138, should I use the single file to merge the code of PR raise and Issue raise or make a separate YAML file?

**Comment by jfmartinz** [comment]
its actually better if those things are in a single file but since y ou arlraedy seperate, so its okay. No wories.

**Comment by Rajneeshkarya** [comment]
Yes! Okay I will create a separate YAML for the issue raise

**Comment by jfmartinz** [comment]
The PR raised is already working, but not the PR merged. Idk what the problem haha.

**Comment by Rajneeshkarya** [comment]
hi @jfmartinz,

PR merged is done by another contributor, if you can create this issue and assign it to me then it would help in GSSOC'24.

**Comment by jfmartinz** [comment]
Can you create the issue, I will assiged it to you

**Comment by Rajneeshkarya** [comment]
Hi @jfmartinz 

Sure, I will create the issue :)

**Pull request merged**
