### PR TITLE
Category : DSA section: learning websites

### PR DESCRIPTION
**Pull request by anu03k**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [ ] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [ ] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Comment by jfmartinz** [comment]
You didn't followo the format for adding a new resource and section, it is located in the [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)

**Comment by anu03k** [comment]
please review it again

**Review by jfmartinz — CHANGES_REQUESTED** [review]
Changes to make:
1. Add each table a description and start with '>' before the description. Section that you should add description, Website to Learn DSA,  DSA Language, DSA Pattern, Books, Blogs and Articles, Videos and Tutorials
2. Remove [Why Learn Algorithms and Data Structures (DSA)?](https://github.com/jfmartinz/ResourceHub/blob/323dd643780caa113235ddcdacb08612e3e415ac/DSA/readme.md#why-learn-algorithms-and-data-structures-dsa) instead add a description at the top (below the readme title)
3. [Practice Problems](https://github.com/jfmartinz/ResourceHub/blob/323dd643780caa113235ddcdacb08612e3e415ac/DSA/readme.md#practice-problems) combine it into the [Websites to Learn DSA](https://github.com/jfmartinz/ResourceHub/blob/323dd643780caa113235ddcdacb08612e3e415ac/DSA/readme.md#websites-to-learn-dsa)

**Review by jfmartinz — COMMENTED** [review]
I already merged someone else pr about this: 

https://github.com/jfmartinz/ResourceHub/tree/main/Data%20Structures%20and%20Algorithm%20(DSA)

Thats why I always said that always look for the same issue so this wont happen. You can instead add the resources and section that doesnt exist on that URL and add your resources into that URL and Ill merged it. SOrry for this didnt notice ill give level 2

**Pull request closed without merging**
