### PR TITLE
Python Section formatting

### PR DESCRIPTION
**Pull request by sau-mili**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

Redo of the previous pull

- 
-
-

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Comment by sau-mili** [comment]
@jfmartinz check before any other pull on same python folder please.

**Review by jfmartinz — APPROVED** [review]
Thanks @sau-mili

**Comment by sau-mili** [comment]
is there anything wrong with this PR? it was not merged?

**Comment by jfmartinz** [comment]
Conflict, just create a new branch and then copy paste your changes to that, and then push again and create PR

**Pull request closed without merging**
