### PR TITLE
Programming Languages-Adding Resources in different programming languages

### LINKED ISSUE #765: 💡 [FEATURE] - Programming Languages - Adding Interview Prep and Foundations of Programming Course in Different Programming Languages
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Providing a Course on the above topic for 4 Programming Languages - C++, Python, Java, JavaScript.

### Explain your solution

Google Dev Tech Guide provides courses on these topics(For Free), So adding these resources  and making others aware will surely help the community.

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MIpaltan007**
Closes #765 

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by MIpaltan007** [comment]
@jfmartinz I have added those resources which I had mentioned in #765 . Add labels to it. As I have contributed for different programming languages so If possible, can you add a level2 label to it.

**Comment by MIpaltan007** [comment]
> @jfmartinz I have added those resources which I had mentioned in #765 . Add labels to it. As I have contributed for different programming languages so If possible, can you add a level2 label to it.

@jfmartinz Please have a look at it

**Review by jfmartinz — CHANGES_REQUESTED** [review]
In java:
image

**Comment by MIpaltan007** [comment]
@jfmartinz Just now commited the requested change. It was a silly mistake from my side, writing <td> instead of </td>. Hope it is fine now

**Comment by MIpaltan007** [comment]
> @jfmartinz Just now commited the requested change. It was a silly mistake from my side. Hope it is fine now

@jfmartinz Please have a look

**Review by jfmartinz — APPROVED** [review]

**Comment by jfmartinz** [comment]
Just solve the merge conlifct

**Comment by MIpaltan007** [comment]
> Just solve the merge conlifct

Solved now, Have a look

**Review by jfmartinz — APPROVED** [review]

**Pull request merged**
