### PR TITLE
Added "Licensing Page" Reflecting "MIT Licence"

### LINKED ISSUE #1377: Feature 🌟: Add "Licensing Page" Reflecting "MIT Licence"
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Hey @jfmartinz ,
Here is the feature request i want to implement - 

To provide clear information about the licensing of the website's content and code, we need to add a dedicated "Licensing Page" that reflects the use of the MIT License. 
This page will help users understand the terms under which they can use, modify, and distribute the website's resources.

Like this : 

image

### Explain your solution

**Steps to Implement**
1. Create Licensing Page :
- Develop a new page titled "Licensing" accessible from the main navigation menu or footer.
2. Content for Licensing Page:
- Include a brief introduction explaining the importance of licensing.
- Provide the full text of the MIT License.

Could you please assign me this issue.

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @jfmartinz 
issue closes #1377 

## What Changes I Made - 
- I have **added a dedicated "Licensing Page"** that reflects the use of the MIT License. 
- **Added Accessible link** to the license section in home page.
- Integrated Footer.
- Integrated Scroll to top button.
- also **Added a Favicon** to the page.

https://github.com/jfmartinz/ResourceHub/assets/131389695/586ef1c1-b422-485c-8001-e846bcd1e80a

## Type of change
- [x] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

Please take a look and review it.

### CODE REVIEW

**Comment by aslams2020** [comment]
@jfmartinz

**Comment by jfmartinz** [comment]
Maybe remove the footer and just add a 'back' button that redirect to a home again, and t hen ill merged your PR

**Comment by aslams2020** [comment]
Sure @jfmartinz

**Comment by aslams2020** [comment]
@jfmartinz Done.. Please take a look

**Comment by jfmartinz** [comment]
Thanks

**Pull request merged**
