### PR TITLE
ReactJS updated+grammartical errors

### PR DESCRIPTION
**Pull request by sau-mili**
# Pull Request

## Description
Please include a summary of the changes and the related issue.  

Closes # 

## Type of change
- [ ] Adding a new Resource
- [ ] Adding a new Category
- [x] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

### CODE REVIEW

**Review by jfmartinz — CHANGES_REQUESTED** [review]
You forgot to add indentation for Books section

**Comment by jfmartinz** [comment]
Current:
- Books
- Free books
- Paid Books

Expected
- Books
   - Free books
   - Paid Books

**Comment by sau-mili** [comment]
Can you please check now?

**Review by jfmartinz — APPROVED** [review]
LGTM!

**Pull request merged**
