### PR TITLE
Chess Game Added

### LINKED ISSUE #942: 💡 [FEATURE] - Add Chess game for webdevelopment frontend project
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

I will add a chess game for web development frontend projects 

### Explain your solution

_No response_

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
# Pull Request

## Description
I have added the chess game in web development frontend projects 

Closes #942  

## Type of change
- [x] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [ ] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

https://github.com/jfmartinz/ResourceHub/assets/118350936/0ea1fbb4-ee97-4b33-a1dd-17cccc75d198

### CODE REVIEW

**Review by jfmartinz — CHANGES_REQUESTED** [review]
Add the source code or the guide for that project , dont add it into our project. Read contributing.md, you should add it as a resouce

**Comment by Ayushmaanagarwal1211** [comment]
Oh ok i am working on it

**Comment by jfmartinz** [comment]
Thanks

**Comment by jfmartinz** [comment]
Give the URL of that source code and then creaate a short description about the project. YOu can refer to existing resource to get an idea

**Pull request closed without merging**
