### PR TITLE
Basic webpage for opportunities added

### LINKED ISSUE #1339: 💡 [FEATURE] -Create an Opportunities page
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

An opportunities page with jobs, internships and hackathon options

### Explain your solution

_No response_

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sau-mili**
# Pull Request
resolves #1339 
## Description
Please include a summary of the changes and the related issue.  
This pull has the basic website, with main section, the navbar, footer and slider. In next pulls I will be adding the sub-sections of the page.

## Type of change
- [ ] Adding a new Resource
- [ ] Adding a new Category
- [ ] Documentation enhancement or fixes
- [x] Website enhancement or fixes

## Checklist:
- [x] I read carefully [CONTRIBUTING.md](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Screenshots (if appropriate):

Please add screenshots to help explain your changes.

### CODE REVIEW

**Comment by jfmartinz** [comment]
Did you create seperate html for it?

**Comment by jfmartinz** [comment]
Can you just add it inside the nav items?

**Comment by sau-mili** [comment]
Yes a separate html, adding to navbar

**Comment by sau-mili** [comment]
Please check now

**Comment by jfmartinz** [comment]
Can I see the output in your end? I cant really tell just by looking at the changes.

**Comment by jfmartinz** [comment]
or even a short mp4 to demo how it looks, for example, when I clicked the navigation item, where would it go? What would happen if I clicked jobs or opportunities? Does the search component work? Just to get an idea

**Comment by sau-mili** [comment]
No, the separate sections doesn't work yet. To keep commit history clean, I have added the overall UI first, I will be adding other functionalities in next PR(s). The navbar work now, it directs to Opportunities page

**Comment by jfmartinz** [comment]
Sounds good. Thanks

**Pull request merged**
