### PR TITLE
Adding resources in Hindi language 

### PR DESCRIPTION
**Pull request by Official-Lovely-kumari**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by Official-Lovely-kumari** [comment]
Please help me I think something gone wrong..

**Comment by jfmartinz** [comment]
> Please help me I think something gone wrong..

Please go to this [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line#competing-line-change-merge-conflicts) and read the instructions carefully, this link should help

**Comment by Official-Lovely-kumari** [comment]
> > Please help me I think something gone wrong..
> 
> Please go to this [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line#competing-line-change-merge-conflicts) and read the instructions carefully, this link should help

Thanks a lot for your help..

**Comment by Official-Lovely-kumari** [comment]
Conflicts solved !

**Pull request merged**
