### PR TITLE
Auto-Commenting Feature for PR Merged

### PR DESCRIPTION
**Pull request by A-b-i-r-a-m-i-G-S**
### Fixes Issue
Auto-Commenting Feature for PR Merged #140 

### Description: 
To enhance our communication and acknowledgment process, we're implementing an auto-commenting feature for specific events within our project repository. This feature will automatically generate comments under the following circumstances:
PR Merged: Upon the successful merging of a pull request (PR), an auto-comment will be added to the corresponding issue, indicating that the PR has been merged and expressing gratitude to the contributor for their valuable contribution.
This is the message that should pop up: "[Auto-Comment]: 🎉 Your pull request has been successfully merged! 🎉 Thank you for your valuable contribution to our project. Your efforts are greatly appreciated. Feel free to reach out if you have any more contributions or if there's anything else we can assist you with. Keep up the fantastic work! 🚀

### Screenshot:
Screenshot 2024-05-14 110511

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I have tested the functionality of the feature before making the pull request.

### CODE REVIEW

**Review by jfmartinz — APPROVED** [review]

**Comment by jfmartinz** [comment]
Btw @A-b-i-r-a-m-i-G-S, I think I need to add something on the project, in your end its working, in this project its not. What did you add to makae it work?

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@jfmartinz I didn't add anything extra to make it work. To help understand where the bug is could you share a screenshot of the repository settings for actions (Settings>Actions>General>Workflow permissions)?

**Comment by jfmartinz** [comment]
It has read n write:

image

**Comment by jfmartinz** [comment]
Maybe I need to add something or update this:

image

**Comment by A-b-i-r-a-m-i-G-S** [comment]
@jfmartinz check this out. It might resolve the issue you're facing.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories

**Pull request merged**
