### PR TITLE
Added links for easier navigation

### LINKED ISSUE #783: 🐞 [BUG] - All available categories not mentioned in the main README.md
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

The main README.md has a section containing available Categories in this project. But it is not up-to-date.
Screenshot_2024-06-03-17-50-52-157

### Expected behavior

I would like to update all the categories that have been available so far. I will add the category 'Data Structure and Algorithms', and new sections under Programming language containing all the languages for easy navigation.

### Steps to reproduce

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by samarpitadas**
# Closes #783 

Added links for the languages category to README.md for easier navigation.

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by jfmartinz** [comment]
Conflict, please resolve it thanks

**Review by jfmartinz — CHANGES_REQUESTED** [review]
Please dont remove this:

- [Frontend Development](https://github.com/jfmartinz/ResourceHub/tree/main/Web%20Development/Frontend%20Development)

**Comment by samarpitadas** [comment]
@jfmartinz please see, I have added it back

**Review by jfmartinz — APPROVED** [review]

**Comment by jfmartinz** [comment]
solve the conflict

**Comment by samarpitadas** [comment]
@jfmartinz yup it's done. Please do check now

**Comment by jfmartinz** [comment]
Solve the conflict again. Then I can merge it thans

**Comment by samarpitadas** [comment]
@jfmartinz I had some troubles regarding solving the conflict so I made a new PR.(# 911). I am closing this PR.

**Pull request closed without merging**
