### PR TITLE
Programming Languages - Adding DSA Resources

### LINKED ISSUE #399: 💡 [FEATURE] - Adding A Section for Data Structures and Algorithms(DSA)
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Explain feature request

Data Structures and Algorithms (DSA) are the most demanded skills an interviewer looks for in a candidate in an interview. Many times candidates are confused about certain things like what to study, where to study, are these enough? . A dedicated section would really help the candidates crack their interviews and help them land their dream jobs.

### Explain your solution

I would like to share all the Data Structures and their description. Along with that YouTube Channels, Courses, Sites to practice and learn and some useful resources. Also I have one doubt, I have pdfs saved in my local system, how can I upload them so that others too can access them.

### Any alternative approaches/features

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MIpaltan007**
Closes #399 

### Checklist:

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by MIpaltan007** [comment]
@jfmartinz I have added a section for Data Structures and Algorithms(DSA). Please authorize in Vercel, and also merge this one. Also add the gssoc labels and level lables. If possible, can you add level3 label for this one

**Comment by jfmartinz** [comment]
The directory of this should be the root folder not in the programming languages. Thanks

**Comment by jfmartinz** [comment]
then can you create more section in table of contents sbout DSA in each language, and create 1 for JavaScript or any language youre comfortable and the content would be the DSA tackled on that. For example Array in JS or Graph and many more and provide resources for it

**Comment by MIpaltan007** [comment]
I am not that much capable of creating contents in multiple language. Anyways, you said the directory should be a root folder. That means instead of creating a folder inside Programming Languages, I have to create a separate folder like App Development, Data Science, Am I Right???

**Comment by MIpaltan007** [comment]
> I am not that much capable of creating contents in multiple language. Anyways, you said the directory should be a root folder. That means instead of creating a folder inside Programming Languages, I have to create a separate folder like App Development, Data Science, Am I Right???

@jfmartinz Any response from your side??

**Pull request closed without merging**
