### PR TITLE
Scroll to top button added

### PR DESCRIPTION
**Pull request by zalabhavy**
issue no #621
### Description: 
Here I have added Scroll to top button with functionality and give them style so looks good.
image
### Resource URL: 
- https://www.w3schools.com/howto/howto_js_scroll_to_top.asp

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [x] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [x] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

> fill the bracket with x. Something like this [x]

### CODE REVIEW

**Comment by zalabhavy** [comment]
@jfmartinz **Please check it and merge it and please it is possible to add level 2**

**Comment by jfmartinz** [comment]
Can you give a mp4 about its working. We're still working on the preview in Vercel

**Comment by zalabhavy** [comment]
@jfmartinz you can check this : 
https://www.loom.com/share/e452e63e79aa46ed920a122771827c63

**Comment by zalabhavy** [comment]
@jfmartinz Please check it and merge !

**Pull request merged**
