### PR TITLE
Programming Languages -  "C++" Complete Resources

### PR DESCRIPTION
**Pull request by MastanSayyad**
**IMPORTANT:** When creating your Pull Request, please use the following format for the title: `Category - Resource Name & Section`  

PR Title samples:

- `Web development - CSS Portal & Tools`
- `Web development - Leetcode & Challenges`

### Closes Issue
Fixes Issue #333

### Description: 
Hey @jfmartinz I have added all resources for C++
```
./Programming Languages
       /C++
         / readme.md
```
Please take a look and do let me know,
Hope it helps. (also pls do not forget to add labels)

### Checklist:
Before submitting your pull request, ensure that you have completed the following tasks: 

- [X] I have carefully reviewed and adhered to the [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) before creating this pull request.
- [X] I followed the prescribed PR title template. _(Check this if you're adding a resource)_

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@jfmartinz, I have been working on  the resources of "C, Kotlin, Typescript, Rust, Go lang, SQL and System Design" resources so make sure you don't assign these languages to anyone else, and sorry for little delays as I am trying to cover everything with the best resources, Thank you!!

**Review by jfmartinz — APPROVED** [review]

**Comment by jfmartinz** [comment]
Np thanks

**Comment by MastanSayyad** [comment]
Thank you @jfmartinz,  I hope my contribution add some value to this repo

**Comment by jfmartinz** [comment]
Keep going @MastanSayyad

**Pull request merged**
